<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BLRL5CG0287TTQ" name="com.tmb.auto.tests.HomePageTest" tests="1" failures="0" timestamp="2023-06-01T13:41:55 IST" time="17.557" errors="1">
  <testcase name="loginHomePageTest" time="17.557" classname="com.tmb.auto.tests.HomePageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tmb.reports.ExtentLogger.pass(ExtentLogger.java:6)
at com.tmb.utils.SeleniumUtils.sendKeys(SeleniumUtils.java:35)
at com.tmb.pages.LoginPage.setUserName(LoginPage.java:18)
at com.tmb.pages.LoginPage.loginToApplication(LoginPage.java:36)
at com.tmb.auto.tests.HomePageTest.loginHomePageTest(HomePageTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginHomePageTest -->
  <system-out/>
</testsuite> <!-- com.tmb.auto.tests.HomePageTest -->
